/* ============================================
   Project data — edit this file to update projects
   ============================================ */

const SKILLS = [
  { name: "WordPress", ico: "W" },
  { name: "Shopify", ico: "S" },
  { name: "Elementor Pro", ico: "E" },
  { name: "WooCommerce", ico: "Wc" },
  { name: "HTML5", ico: "H" },
  { name: "CSS3", ico: "C" },
  { name: "JavaScript", ico: "JS" },
  { name: "Liquid", ico: "L" },
  { name: "Bootstrap", ico: "B" },
  { name: "Responsive", ico: "R" },
  { name: "Speed / CWV", ico: "⚡" },
  { name: "SEO", ico: "🔍" },
  { name: "Git", ico: "G" },
  { name: "GitHub", ico: "GH" },
  { name: "Figma", ico: "F" },
  { name: "Photoshop", ico: "Ps" },
];

const WORDPRESS_PROJECTS = [
  {
    slug: "betterhood",
    name: "Betterhood",
    client: "Betterhood",
    industry: "Preventive Pain-Care",
    type: "Corporate + Commerce (WordPress + Shopify)",
    status: "Live",
    date: "2024",
    duration: "8 weeks",
    url: "https://betterhood.in/",
    description:
      "Science-backed preventive pain-care brand featuring a dual WordPress + Shopify architecture. WordPress hosts the marketing site with rich editorial content; Shopify powers a seamless commerce experience with custom cross-domain JS integrations.",
    tech: ["WordPress", "Shopify", "ACF", "Custom JS", "Liquid", "REST API"],
    responsibilities: [
      "End-to-end WordPress theme architecture",
      "Cross-platform WordPress ↔ Shopify integration",
      "Custom JS for product syncing and cart handoff",
      "Speed and Core Web Vitals optimisation",
    ],
    features: [
      "Editorial CMS with ACF flexible layouts",
      "Custom product blocks pulling live Shopify data",
      "Blog + condition library taxonomies",
      "Accessible custom navigation",
    ],
    challenges:
      "Bridging WordPress and Shopify without sacrificing SEO or performance while keeping the editorial experience effortless for the client team.",
    performance: { speed: 96, seo: 100, a11y: 98, best: 100 },
  },
  {
    slug: "cometrank",
    name: "CometRank",
    client: "CometRank",
    industry: "SEO SaaS",
    type: "SaaS Marketing Site",
    status: "Live",
    date: "2025",
    duration: "6 weeks",
    url: "https://cometrank.ai/",
    description:
      "AI-powered SEO SaaS platform — WordPress marketing site with animated dashboard mockups, agent-based product sections, and a conversion-focused demo-booking flow.",
    tech: ["WordPress", "ACF Pro", "GSAP", "Custom JS", "Elementor"],
    responsibilities: [
      "Custom theme built from scratch",
      "Interactive dashboard mockup animations",
      "Demo booking flow with CRM integration",
      "SEO architecture and schema",
    ],
    features: [
      "Animated hero with agent-driven interactions",
      "Modular case-study blocks",
      "Pricing table with dynamic ACF fields",
      "Blog + knowledge base sections",
    ],
    challenges:
      "Communicating a technical AI product visually without slowing the site down — solved with lazy-loaded animation modules.",
    performance: { speed: 94, seo: 100, a11y: 97, best: 100 },
  },
  {
    slug: "procloz",
    name: "Procloz",
    client: "Procloz",
    industry: "HR & Payroll SaaS",
    type: "SaaS Marketing Site",
    status: "Live",
    date: "2024",
    duration: "5 weeks",
    url: "https://procloz.com/",
    description:
      "HR & payroll SaaS platform — custom WordPress build with advanced ACF fields and dynamic content blocks powering a scalable multi-region site.",
    tech: ["WordPress", "ACF Pro", "Custom Blocks", "Gutenberg"],
    responsibilities: [
      "Theme architecture and CPT design",
      "ACF flexible content blocks",
      "Multi-region routing and localisation",
      "SEO and performance tuning",
    ],
    features: [
      "Modular block library for marketing team",
      "Regional pricing and content variants",
      "Custom form flows with validation",
      "Case study & solution pages",
    ],
    challenges:
      "Building a system flexible enough for a growing marketing team while keeping each page fast and predictable.",
    performance: { speed: 92, seo: 100, a11y: 96, best: 100 },
  },
  {
    slug: "india-talents",
    name: "India Talents",
    client: "India Talents",
    industry: "Talent Management",
    type: "Editorial + Portfolio",
    status: "Live",
    date: "2023",
    duration: "7 weeks",
    url: "https://www.indiatalents.com/",
    description:
      "Creative talent management & production platform — covering ad films, fashion weeks and full talent management with a rich portfolio experience.",
    tech: ["WordPress", "ACF", "Custom Post Types", "Elementor"],
    responsibilities: [
      "Talent CPT and taxonomy design",
      "Portfolio gallery UI",
      "Custom filtering and search",
      "Image performance pipeline",
    ],
    features: [
      "Filterable talent roster",
      "Video-first case study pages",
      "Editorial magazine section",
      "Contact & booking flow",
    ],
    challenges:
      "Handling a media-heavy site with hundreds of images without hurting page speed — solved via responsive images and lazy loading.",
    performance: { speed: 90, seo: 98, a11y: 95, best: 100 },
  },
  {
    slug: "planet-ganges",
    name: "Planet Ganges",
    client: "Planet Ganges",
    industry: "Strategy Consulting",
    type: "Corporate Website",
    status: "Live",
    date: "2024",
    duration: "4 weeks",
    url: "https://planetganges.com/",
    description:
      "Strategy consulting firm — custom WordPress build with Elementor, structured service and case-study architecture, and a refined editorial feel.",
    tech: ["WordPress", "Elementor Pro", "ACF", "Custom CSS"],
    responsibilities: [
      "Elementor theme customisation",
      "Case-study CPT design",
      "Custom animations",
      "SEO structure",
    ],
    features: ["Case-study library", "Service pages", "Team bios", "Insights blog"],
    challenges:
      "Making Elementor feel premium — achieved through custom CSS overrides and a strict design system.",
    performance: { speed: 91, seo: 98, a11y: 96, best: 100 },
  },
  {
    slug: "softude-ai",
    name: "Softude AI",
    client: "Softude",
    industry: "AI Services",
    type: "Corporate Website",
    status: "Live",
    date: "2024",
    duration: "6 weeks",
    url: "https://softude.ai/",
    description:
      "AI company branding & website built on WordPress with custom JS animations and dynamic sections that reflect the brand's forward-looking positioning.",
    tech: ["WordPress", "Custom JS", "GSAP", "ACF"],
    responsibilities: [
      "Custom theme development",
      "Interactive animation system",
      "Reusable content blocks",
      "SEO and performance",
    ],
    features: ["Animated hero", "Service pages with case studies", "Blog", "Contact + demo forms"],
    challenges:
      "Keeping visually rich animations performant on lower-end devices — solved with reduced-motion fallbacks.",
    performance: { speed: 93, seo: 99, a11y: 97, best: 100 },
  },
  {
    slug: "evendigit",
    name: "EvenDigit",
    client: "EvenDigit",
    industry: "Digital Agency",
    type: "Corporate Website",
    status: "Live",
    date: "2023",
    duration: "8 weeks",
    url: "https://www.evendigit.com/",
    description:
      "Digital agency website with performance-first WordPress architecture, custom animations and a case-study system built for scale.",
    tech: ["WordPress", "Custom Theme", "GSAP", "ACF"],
    responsibilities: [
      "Custom theme from scratch",
      "Case-study CPT with dynamic filtering",
      "Portfolio image pipeline",
      "SEO",
    ],
    features: ["Filterable case studies", "Service pages", "Team + culture", "Careers section"],
    challenges: "Balancing brand storytelling with technical rigor across dozens of case studies.",
    performance: { speed: 94, seo: 100, a11y: 97, best: 100 },
  },
];

const SHOPIFY_PROJECTS = [
  {
    slug: "oulac-cosmetics",
    name: "Oulac Cosmetics",
    client: "Oulac",
    industry: "Beauty & Cosmetics",
    theme: "Custom (Dawn base)",
    status: "Live",
    date: "2024",
    url: "https://www.oulaccosmetics.com/",
    description:
      "Premium cosmetics — custom Shopify build with metafields, metaobjects & a JavaScript product configurator that lets customers explore shades and finishes.",
    tech: ["Shopify", "Liquid", "Metafields", "Metaobjects", "Custom JS", "Shopify Markets"],
    apps: ["Judge.me", "Klaviyo", "Loop Subscriptions", "Searchanise"],
    features: [
      "Shade/finish product configurator",
      "Metaobject-driven ingredient pages",
      "Custom bundle builder",
      "Localised Markets storefront (multi-currency)",
    ],
    liquid: [
      "Custom sections for hero, bundles, quiz",
      "Metafield-powered PDP",
      "AJAX cart with side drawer",
      "Reusable snippets for card variants",
    ],
    stats: { products: 84, collections: 12, pages: 22, apps: 8, speed: 88, conversionLift: "+29%" },
    seo: ["Structured data on all PDPs", "Schema for reviews & FAQs", "Optimised meta templates"],
  },
  {
    slug: "elan-india",
    name: "Elan India",
    client: "Elan India",
    industry: "Luxury Cosmetics",
    theme: "Custom",
    status: "Live",
    date: "2024",
    url: "https://www.elanindia.co/",
    description:
      "Luxury cosmetics e-commerce with a bespoke Shopify theme and enhanced UX flows tuned for a high-AOV customer.",
    tech: ["Shopify", "Liquid", "Custom JS", "Metafields"],
    apps: ["Klaviyo", "Judge.me", "Shopify Inbox"],
    features: [
      "Luxury-tier PDP with parallax gallery",
      "Custom checkout upsells",
      "Editorial collection pages",
      "Loyalty integration",
    ],
    liquid: ["Custom sections", "Snippet library for cards", "Metafield-driven storytelling"],
    stats: { products: 62, collections: 9, pages: 18, apps: 6, speed: 90, conversionLift: "+22%" },
    seo: ["Product schema", "Rich collection meta", "Optimised sitemaps"],
  },
  {
    slug: "bear-fruit-jewelry",
    name: "Bear Fruit Jewelry",
    client: "Bear Fruit",
    industry: "Artisan Jewelry",
    theme: "Custom",
    status: "Live",
    date: "2024",
    url: "https://bearfruitjewelry.com/",
    description:
      "Artisan jewelry store with metafield-driven product pages and a custom engraving feature built directly into the PDP.",
    tech: ["Shopify", "Liquid", "Metafields", "Line Item Properties"],
    apps: ["Klaviyo", "Loox", "Recharge"],
    features: [
      "Live engraving preview",
      "Metafield-driven materials & care",
      "Wishlist with local storage",
      "Gift wrap upsells",
    ],
    liquid: [
      "Custom engraving section",
      "PDP variants + metafield blocks",
      "Cart line-item property display",
    ],
    stats: { products: 140, collections: 14, pages: 20, apps: 7, speed: 89, conversionLift: "+18%" },
    seo: ["Category schema", "Product FAQ schema"],
  },
  {
    slug: "yokkao-asia",
    name: "Yokkao Asia",
    client: "Yokkao",
    industry: "Sports & Apparel",
    theme: "Custom",
    status: "Live",
    date: "2023",
    url: "https://asia.yokkao.com/",
    description:
      "Premium Muay Thai gear — high-performance store for Asian markets with a custom filter UX and multi-region storefront.",
    tech: ["Shopify", "Liquid", "Custom JS", "Shopify Markets"],
    apps: ["Klaviyo", "Judge.me", "Searchanise"],
    features: [
      "Advanced filter UX with instant results",
      "Multi-region pricing",
      "Athlete stories collection",
      "Custom size guide modal",
    ],
    liquid: ["Filter section", "Region-aware price snippets", "Athlete CPT-like metaobjects"],
    stats: { products: 210, collections: 22, pages: 26, apps: 8, speed: 91, conversionLift: "+31%" },
    seo: ["Product schema", "Multilingual meta"],
  },
  {
    slug: "ageless-zen",
    name: "Ageless Zen",
    client: "Ageless Zen",
    industry: "Wellness & Anti-ageing",
    theme: "Custom",
    status: "Live",
    date: "2024",
    url: "https://agelesszen.us/",
    description:
      "Wellness & anti-ageing brand store with subscription flows and before/after sections that build trust and drive AOV.",
    tech: ["Shopify", "Liquid", "Recharge", "Metafields"],
    apps: ["Recharge", "Klaviyo", "Loox"],
    features: [
      "Subscription-first PDPs",
      "Before/after gallery",
      "Ingredient science pages",
      "Quiz-based recommendations",
    ],
    liquid: ["Subscription selector", "Before/after slider", "Quiz result binding"],
    stats: { products: 34, collections: 6, pages: 14, apps: 6, speed: 92, conversionLift: "+34%" },
    seo: ["Ingredient FAQ schema", "Product schema"],
  },
  {
    slug: "pluscenta",
    name: "Pluscenta",
    client: "Pluscenta",
    industry: "Skincare",
    theme: "Custom",
    status: "Live",
    date: "2024",
    url: "https://pluscenta.com/",
    description:
      "Beauty & skincare store with a custom theme, collection pages and conversion-focused PDPs including trust-building elements throughout.",
    tech: ["Shopify", "Liquid", "Metafields", "Custom JS"],
    apps: ["Klaviyo", "Judge.me", "Shopify Search & Discovery"],
    features: [
      "Ingredient callout modules",
      "Routine builder",
      "Editorial collection pages",
      "Sticky ATC on PDP",
    ],
    liquid: ["Routine builder section", "Ingredient snippets", "Editorial layouts"],
    stats: { products: 46, collections: 8, pages: 16, apps: 5, speed: 90, conversionLift: "+25%" },
    seo: ["Rich meta", "Product schema"],
  },
  {
    slug: "petglow-india",
    name: "PetGlow India",
    client: "PetGlow",
    industry: "Pet Care",
    theme: "Custom",
    status: "In Development",
    date: "2026",
    url: "https://petglow-india.myshopify.com/",
    description:
      "Pet care brand — Shopify store currently in development. Custom theme with playful yet premium aesthetic aimed at Indian pet parents.",
    tech: ["Shopify", "Liquid", "Metafields", "Custom JS"],
    apps: ["Klaviyo", "Judge.me"],
    features: ["Pet profile quiz", "Subscription plans", "Editorial care guides"],
    liquid: ["Quiz section", "Subscription selector", "Care guide layouts"],
    stats: { products: 24, collections: 5, pages: 12, apps: 4, speed: 90, conversionLift: "TBD" },
    seo: ["Product schema", "FAQ schema"],
  },
];
